### ISSUE TITLE
@lucide/vue: all 1820 icon declarations reference unbound `FunctionalComponent` since 1.42.0 (icons silently typed as `any`)

### ISSUE THREAD

**Issue by DK5EN** [lucide-icons/lucide#4837]
### Package

- [ ] lucide
- [ ] lucide-react
- [x] @lucide/vue
- [ ] @lucide/svelte
- [ ] @lucide/angular
- [ ] @lucide/astro
- [ ] lucide-react-native
- [ ] lucide-preact
- [ ] lucide-solid
- [ ] lucide-static
- [ ] @lucide/icons
- [ ] lucide-vue-next (deprecated)
- [ ] lucide-svelte (deprecated)
- [ ] lucide-angular (deprecated)
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

1.44.0

### Can you reproduce this in the latest version?

- [x] Yes
- [ ] No

### Browser

- [ ] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [x] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [x] macOS
- [ ] ChromeOS
- [ ] iOS
- [ ] Android
- [ ] Other/not relevant

### Description

Since 1.42.0, the bundled type declarations in `@lucide/vue` reference an identifier that the file never binds, so **every icon resolves to an error type** (effectively `any`).

`dist/lucide-vue.d.ts` line 1 imports the Vue type under an alias:

```ts
import { SVGAttributes, FunctionalComponent as FunctionalComponent$1 } from 'vue';
```

The two hand-written declarations use the alias correctly:

```ts
type LucideIcon = FunctionalComponent$1<LucideProps>;                    // line 45
declare const Icon: FunctionalComponent$1<LucideProps & IconProps>;      // line 27399
```

But all 1820 generated icon declarations use the **unaliased** name, which is not in scope:

```ts
declare const AArrowDown: FunctionalComponent<LucideProps>;   // line 58
declare const Check: FunctionalComponent<LucideProps>;
// ... 1820 occurrences
```

`tsc` reports 1820 errors:

```
dist/lucide-vue.d.ts(58,27): error TS2552: Cannot find name 'FunctionalComponent'. Did you mean 'FunctionalComponent$1'?
dist/lucide-vue.d.ts(71,25): error TS2552: Cannot find name 'FunctionalComponent'. Did you mean 'FunctionalComponent$1'?
... (the remaining ones as TS2304)
```

All three declaration entry points are affected: `dist/lucide-vue.d.ts`, `dist/lucide-vue.prefixed.d.ts`, `dist/lucide-vue.suffixed.d.ts` (1820 occurrences each).

**Why this is easy to miss:** `skipLibCheck: true` — which `@vue/tsconfig` enables by default — suppresses the diagnostic entirely. Builds and `vue-tsc -b` stay green while every icon is silently `any`. In our project the only thing that surfaced it was `typescript-eslint`'s `strictTypeChecked` preset, which flagged `no-unsafe-assignment` / `no-unsafe-return` on every icon usage site after upgrading from 1.41.0.

**Affected versions:** 1.42.0, 1.43.0, 1.44.0. Last good release is **1.41.0**, whose declaration file starts with the unaliased `import { FunctionalComponent, SVGAttributes } from 'vue';` and is internally consistent.

**Not affected:** `lucide-react`, `lucide-preact` and `@lucide/svelte` at 1.44.0 — their generated declarations use a namespace import (`import * as react from 'react'`), so the aliasing collision cannot occur. This appears to be specific to the Vue package's named import.

**Suspected cause:** #4806 (merged 2026-09-04) bumped `packages/vue/package.json` from `rollup-plugin-dts@^6.4.1` / `typescript@^5.9.3` to `rollup-plugin-dts@^6.5.1` / `typescript@^6.0.3`. 1.41.0 (released 2026-09-04, before the merge landed in a release) is clean; 1.42.0 (2026-09-07) is the first release after it and is broken. It looks like the dts bundler renames the import to avoid a collision but does not rewrite the generated reference sites.

This may share a root cause with #4823 ("builder exports unresolvable since 1.42.0"), which came out of the same release.

### Steps to reproduce

```bash
mkdir repro && cd repro
npm init -y
npm i typescript@6.0.3 vue@3.5.42 @lucide/vue@1.44.0

printf "import { Check } from '@lucide/vue'\nexport const Icon = Check\n" > probe.ts

cat > tsconfig.json <<'EOF'
{
  "compilerOptions": {
    "strict": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "noEmit": true,
    "skipLibCheck": false
  },
  "include": ["probe.ts"]
}
EOF

npx tsc -p .
```

Observed: 1820 errors, starting with

```
node_modules/@lucide/vue/dist/lucide-vue.d.ts(58,27): error TS2552: Cannot find name 'FunctionalComponent'. Did you mean 'FunctionalComponent$1'?
```

Expected: no errors.

Setting `"skipLibCheck": true` makes `tsc` exit 0 while `Check` is still an error type — so the failure is silent in most real-world configs.

Pinning to `@lucide/vue@1.41.0` and re-running the same repro produces no errors.

### Checklist

- [x] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by karsa-mistmere** [comment]
Hey @DK5EN,

Thanks, nice catch!

I've posted a fix in https://github.com/lucide-icons/lucide/pull/4841
