### ISSUE TITLE
Vite cannot resolve modules on Windows

### ISSUE THREAD

**Issue by jaads** [lucide-icons/lucide#4159]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [ ] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [x] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] lucide-astro
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.577.0

### Can you reproduce this in the latest version?

- [x] Yes
- [ ] No

### Browser

- [x] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [x] Windows
- [ ] Linux
- [ ] macOS
- [ ] ChromeOS
- [ ] iOS
- [ ] Android
- [ ] Other/not relevant

### Description

After upgrading my Sveltekit project to use Vite 8, my build breaks due to Lucide.
The new backbone of Vite 8 (`rolldown`) cannot resolve some modules, see below:

```bash
error during build:
Build failed with 19 errors:

[UNRESOLVED_IMPORT] Error: Could not resolve './file-audio.svelte' in ../ui-shares/node_modules/@lucide/svelte/dist/icons/file-audio.js
    ╭─[ ../ui-shares/node_modules/@lucide/svelte/dist/icons/file-audio.js:45:25 ]
    │
 45 │ export { default } from "./file-audio.svelte";
    │                         ──────────┬──────────  
    │                                   ╰──────────── Module not found.
    │ 
    │ Help: '../ui-shares/node_modules/@lucide/svelte/dist/icons/file-audio.js' is imported by the following path:
    │         - ../ui-shares/node_modules/@lucide/svelte/dist/icons/file-audio.js
    │         - ../ui-shares/node_modules/@lucide/svelte/dist/icons/index.js
    │         - ../ui-shares/node_modules/@lucide/svelte/dist/lucide-svelte.js
    │         - ../ui-shares/dist/metrics/ArchitectureMetrics.svelte
    │         - ../ui-shares/dist/Vizualization.svelte
    │         - ../ui-shares/dist/index.js
    │         - src/routes/(app)/visualization/+page.svelte
────╯

[UNRESOLVED_IMPORT] Error: Could not resolve './file-audio-2.svelte' in ../ui-shares/node_modules/@lucide/svelte/dist/icons/file-audio-2.js
    ╭─[ ../ui-shares/node_modules/@lucide/svelte/dist/icons/file-audio-2.js:45:25 ]
    │
 45 │ export { default } from "./file-audio-2.svelte";
    │                         ───────────┬───────────  
    │                                    ╰───────────── Module not found.
    │ 
    │ Help: '../ui-shares/node_modules/@lucide/svelte/dist/icons/file-audio-2.js' is imported by the following path:
    │         - ../ui-shares/node_modules/@lucide/svelte/dist/icons/file-audio-2.js
    │         - ../ui-shares/node_modules/@lucide/svelte/dist/icons/index.js
    │         - ../ui-shares/node_modules/@lucide/svelte/dist/lucide-svelte.js
    │         - ../ui-shares/dist/metrics/ArchitectureMetrics.svelte
    │         - ../ui-shares/dist/Vizualization.svelte
    │         - ../ui-shares/dist/index.js
    │         - src/routes/(app)/visualization/+page.svelte
────╯

[UNRESOLVED_IMPORT] Error: Could not resolve './file-badge-2.svelte' in ../ui-shares/node_modules/@lucide/svelte/dist/icons/file-badge-2.js
    ╭─[ ../ui-shares/node_modules/@lucide/svelte/dist/icons/file-badge-2.js:45:25 ]
    │
 45 │ export { default } from "./file-badge-2.svelte";
    │                         ───────────┬───────────  
    │                                    ╰───────────── Module not found.
    │ 
    │ Help: '../ui-shares/node_modules/@lucide/svelte/dist/icons/file-badge-2.js' is imported by the following path:
    │         - ../ui-shares/node_modules/@lucide/svelte/dist/icons/file-badge-2.js
    │         - ../ui-shares/node_modules/@lucide/svelte/dist/icons/index.js
    │         - ../ui-shares/node_modules/@lucide/svelte/dist/lucide-svelte.js
    │         - ../ui-shares/dist/metrics/ArchitectureMetrics.svelte
    │         - ../ui-shares/dist/Vizualization.svelte
    │         - ../ui-shares/dist/index.js
    │         - src/routes/(app)/visualization/+page.svelte
────╯

[UNRESOLVED_IMPORT] Error: Could not resolve './file-check-2.svelte' in ../ui-shares/node_modules/@lucide/svelte/dist/icons/file-check-2.js
    ╭─[ ../ui-shares/node_modules/@lucide/svelte/dist/icons/file-check-2.js:45:25 ]
    │
 45 │ export { default } from "./file-check-2.svelte";
    │                         ───────────┬───────────  
    │                                    ╰───────────── Module not found.
    │ 
    │ Help: '../ui-shares/node_modules/@lucide/svelte/dist/icons/file-check-2.js' is imported by the following path:
    │         - ../ui-shares/node_modules/@lucide/svelte/dist/icons/file-check-2.js
    │         - ../ui-shares/node_modules/@lucide/svelte/dist/icons/index.js
    │         - ../ui-shares/node_modules/@lucide/svelte/dist/lucide-svelte.js
    │         - ../ui-shares/dist/metrics/ArchitectureMetrics.svelte
    │         - ../ui-shares/dist/Vizualization.svelte
    │         - ../ui-shares/dist/index.js
    │         - src/routes/(app)/visualization/+page.svelte
────╯

[UNRESOLVED_IMPORT] Error: Could not resolve './file-code-2.svelte' in ../ui-shares/node_modules/@lucide/svelte/dist/icons/file-code-2.js
    ╭─[ ../ui-shares/node_modules/@lucide/svelte/dist/icons/file-code-2.js:45:25 ]
    │
 45 │ export { default } from "./file-code-2.svelte";
    │                         ───────────┬──────────  
    │                                    ╰──────────── Module not found.
    │ 
    │ Help: '../ui-shares/node_modules/@lucide/svelte/dist/icons/file-code-2.js' is imported by the following path:
    │         - ../ui-shares/node_modules/@lucide/svelte/dist/icons/file-code-2.js
    │         - ../ui-shares/node_modules/@lucide/svelte/dist/icons/index.js
    │         - ../ui-shares/node_modules/@lucide/svelte/dist/lucide-svelte.js
    │         - ../ui-shares/dist/metrics/ArchitectureMetrics.svelte
    │         - ../ui-shares/dist/Vizualization.svelte
    │         - ../ui-shares/dist/index.js
    │         - src/routes/(app)/visualization/+page.svelte
────╯

```
I don't use those mentioned icons in my poroject.

After investigating a bit it seems that  those icons like `file-audio` has been renamed, here into `file-headphone`.
And that "deprecated" icon stubs in `dist/icons/` reference `.svelte` which don't exist anymore and hence cannot be resolved by `rolldown`.

This only happens on Windows for me. 

I assume something needs to be updated in `generateAliasesFiles.ts` maybe like so?

```ts
// before
const output = `export { default } from "./${iconName}${
  separateAliasesFileExtension ? iconFileExtension : ''
}";\n`;

// after
const output = `export { default } from "./${iconName}${aliasImportFileExtension}";\n`;
```

### Steps to reproduce

1. Upgrade Sveltekit project to `vite` 8  and  `@sveltejs/vite-plugin-svelte` to 7 
2. Build the app on Windows (via GH workflow)
3. See build failing

### Checklist

- [x] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by jaads** [comment]
I downgraded lucide, and not it runs though again `"@lucide/svelte": "^0.544.0",`

**Comment by nmitchell-bgl** [comment]
Seeing similar issues on with `@lucide/react: 1.6.0` & vite 8 on macOS.

```
[UNRESOLVED_IMPORT] Error: Could not resolve './icons/a-arrow-down.ts' in ../../node_modules/lucide-react/dist/esm/dynamicIconImports.js
   ╭─[ ../../node_modules/lucide-react/dist/esm/dynamicIconImports.js:9:32 ]
   │
 9 │   "a-arrow-down": () => import('./icons/a-arrow-down.ts'),
   │                                ────────────┬────────────
   │                                            ╰────────────── Module not found.
   │
   │ Help: '../../node_modules/lucide-react/dist/esm/dynamicIconImports.js' is imported by the following path:
   │         - ../../node_modules/lucide-react/dist/esm/dynamicIconImports.js
   │         - ../../node_modules/lucide-react/dynamic.mjs
   │         - src/ui_components/inputs/InputSelect/InputSelect.tsx
   │         - src/gallery/components/GalleryInputSelect.tsx
   │         - src/gallery/components/GalleryInputs.tsx
   │         - src/gallery/GalleryApp.tsx
   │         - src/App.tsx
   │         - src/main.tsx
   │         - index.html
```

**Comment by vugarbbakhishov-hub** [comment]
I checked both reported paths against the current published packages on Windows, and they appear to be resolved now.

For `@lucide/svelte@1.46.0`:

- the tarball contains 2,103 `dist/icons/*.js` exports
- 2,102 of them point to a `.svelte` file, and every target exists (0 broken targets)
- `dist/icons/file-audio.js` now re-exports `./file-headphone.svelte`, which is present
- a minimal production build with Vite 8.3.0, `@sveltejs/vite-plugin-svelte` 7.3.0 and Svelte 5.57.0 completed successfully on Windows
- that build covered both top-level imports (`FileAudio`, `FileBadge2`) and the deep alias import `@lucide/svelte/icons/file-audio`; Vite transformed 4,059 modules without an unresolved import

For `lucide-react@1.46.0`, `dist/esm/dynamicIconImports.mjs` contains 2,102 `.mjs` imports and no `.ts` imports.

So the missing Svelte alias targets from the original report and the React `.ts` specifiers from the later comment are both gone in the latest packages.
